### ISSUE TITLE
Am I able to change background color of entire Widget?

### ISSUE THREAD

**Issue by derens99** [natintosh/intl_phone_number_input#100]
**Describe the bug**
I am basically trying to change the background color of the entire widget, including the background of the flag part. 

I am also running into issues styling the widget, such as border radius.

Are there any examples of styling this library?

**Package version**
LATEST

**Flutter version**
LATEST

**To Reproduce**
Styling widget

**Expected behavior**
Change background color of entire widget, or add border radius.

**Screenshots**
<img width="330" alt="Screen Shot 2020-09-10 at 11 48 32 PM" src="https://user-images.githubusercontent.com/20931708/92855453-467ba480-f3c0-11ea-8ab0-48b60f3e2b15.png">

Here is my attempt at changing the colors to black and corner radius to 5.

** Targeted platforms (please complete the following information):**
 - iOS

**Comment by ClemaX** [comment]
You can try overriding the theme or wrapping `InternationalPhoneNumberInput` in a `Material` widget:
```
return Material(
          type: MaterialType.card, // This makes the corners round
          borderRadius: BorderRadius.circular(5), // Your cornerRadius
          color: Colors.black, // Your background Color
          child: InternationalPhoneNumberInput(
                    selectorTextStyle: TextStyle(color: Colors.white), // Your text color
                    textStyle: TextStyle(color: Colors.white), // Your selector text color
                    // Your settings
          ),
);
```
**Screenshots**
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-01 at 13 22 57](https://user-images.githubusercontent.com/9118612/94803276-5992fa80-03e9-11eb-94c0-4dd4eadcdde0.png)
