### ISSUE TITLE
textFieldController don`t reset value

### ISSUE THREAD

**Issue by pablomagana** [natintosh/intl_phone_number_input#101]
**Describe the bug**

**Package version**
^0.5.1

**To Reproduce**
1. init textFieldController -> TextEditingController controller = TextEditingController()
2. set textFieldController -> textFieldController:controller
3. onPress clear button, run controller.clear()
4. the field keep the last value

**Expected behavior**
My intention is to have a button to clear the phone number field

Thanks

**Comment by cmorsucci** [comment]
show us a piece of code .. because it works correctly for me ..

**Comment by pablomagana** [comment]
`InternationalPhoneNumberInput(
                  locale: Injector().appState.locale,
                  autoValidate:false,
                  focusNode: _node,

                  onInputChanged: (PhoneNumber n) {
                    number =n.phoneNumber;
                  },
                  onInputValidated: (bool value) {
                    setState(() {
                      _validNumber = value;
                    });
                  },
                  inputDecoration: InputDecoration(
                    border: InputBorder.none,
                  ),
                  selectorConfig: SelectorConfig(selectorType: PhoneInputSelectorType.DIALOG),
                  searchBoxDecoration: InputDecoration(
                      contentPadding: EdgeInsets.only(left: 30),
                      alignLabelWithHint: true,
                      border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(40),
                          borderSide: BorderSide(
                            color: Color.fromRGBO(117, 139, 253, 1),
                            width: 1,
                          ))),
                  ignoreBlank: false,
                  selectorTextStyle: TextStyle(color: Colors.black),
                  textFieldController: controller,
                )`
