### ISSUE TITLE
Selector search by isoCode or Abbreviations

### ISSUE THREAD

**Issue by ClemaX** [natintosh/intl_phone_number_input#104]
**Is your feature request related to a problem? Please describe.**
It would be great to search countries by isoCode/Abbreviations: Ex.: 'US'/'USA' instead of typing 'United st...'

**Describe the solution you'd like**
Either use an abbreviation index (Ex.: 'United States of America' -> 'USA') or use the 2 letters isoCode as an index.

**Comment by natintosh** [comment]
Hi @ClemaX that would be a great feature. The package support search for name or translated name and dial code

**Comment by ClemaX** [comment]
This is what I suggest: #106
