### ISSUE TITLE
Input for the label of search

### ISSUE THREAD

**Issue by bakamedi** [natintosh/intl_phone_number_input#111]
Is better to make a input for this `labelText: 'Search by country name or dial code'` so that you can have a single language for display.

`InputDecoration getSearchBoxDecoration() {
    return widget.searchBoxDecoration ??
        InputDecoration(labelText: 'Search by country name or dial code');
}`

![Captura de Pantalla 2020-10-05 a la(s) 12 06 17](https://user-images.githubusercontent.com/6138767/95110229-52c6f900-0703-11eb-89cc-664be7a5e82f.png)

**Comment by natintosh** [comment]
@bakamedi, all you have to do is to update the default text for the search TextField by adding a seachBoxDecorator property
```dart 
searchBoxDecoration: InputDecoration(
labelText: 'Recherche par nom de pays ou indicatif'),
```


```dart
InternationalPhoneNumberInput(
                  initialValue: number,
                  ignoreBlank: false,
                  autoValidateMode: AutovalidateMode.always,
                  textFieldController: controller,
                  focusNode: focusNode,
                  autoFocus: true,
                  inputDecoration:
                      InputDecoration(border: OutlineInputBorder()),
                  locale: 'fr',
                  searchBoxDecoration: InputDecoration(
                      labelText: 'Recherche par nom de pays ou indicatif'),
                  selectorConfig: SelectorConfig(
                    selectorType: PhoneInputSelectorType.BOTTOM_SHEET,
                  ),
                  onInputChanged: (PhoneNumber value) {},
                )
```
