### ISSUE TITLE
Digits automatically appear in input

### ISSUE THREAD

**Issue by taimoor61** [natintosh/intl_phone_number_input#115]
This happens specially with Dominican republic. When u select that country code and enter 1 digit. 3 4 are added by themselves. It happens with some others too but mostly dominican republic.

**Comment by taimoor61** [comment]
It happens with all the countries with 4 digit country codes

**Comment by FRANIAZA** [comment]
set formatInput to false

**Comment by natintosh** [comment]
@taimoor61 I recently pushed to Github that fixed this issue. This fix should be available in the next update

57d626f4a89e55b11b57d9d7d287c3fa68aa2b9f
