### ISSUE TITLE
onInputValidated called many times

### ISSUE THREAD

**Issue by jigarfumakiya** [natintosh/intl_phone_number_input#121]
Hey, Thanks for creating this package.
**Describe the bug**
I am using stateful widget I have wrap InternationalPhoneNumberInput with Form.
But when the user comes to this screen or opens the keyboard for entering a number.
InternationalPhoneNumberInput constantly called onInputValidated (many times like 200-500) and It doesn't stop even if the user enters the number.
**Package version**
  intl_phone_number_input: ^0.5.2+2

**Flutter version**
Flutter 1.22.2 • channel stable

**To Reproduce**
1. Code is below

```dart
Widget countryDropDown() {
  return Form(
    key: formKey,
    child: InternationalPhoneNumberInput(
      onInputChanged: onNumberChanges,
      onInputValidated: (bool value) {
        print(value);
      },
      autoValidateMode: AutovalidateMode.disabled,
      initialValue: number,
      textFieldController: phoneController,
      inputBorder: OutlineInputBorder(),
      selectorConfig: SelectorConfig(
          selectorType: PhoneInputSelectorType.DIALOG,
          backgroundColor: Colors.white,
          useEmoji: false),
      inputDecoration: new InputDecoration(
        border: new OutlineInputBorder(
            borderRadius: BorderRadius.all(Radius.circular(20)),
            borderSide: BorderSide(color: Colors.white)),
        contentPadding: EdgeInsets.all(25),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.all(Radius.circular(20)),
          borderSide: BorderSide(color: Colors.white, width: 5.0),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.all(Radius.circular(20)),
          borderSide: BorderSide(color: Colors.white, width: 5.0),
        ),
      ),
    ),
  );
}
```
**Expected behavior**
I think onInputValidated should call only when the user updated anything unless this doesn't need to call onInputValidated.
And Making the screen performance very leggy and slow

**Screenshots**
![called](https://user-images.githubusercontent.com/11865669/97421863-01411100-1933-11eb-999e-9f00f2d3246c.png)
![Capture](https://user-images.githubusercontent.com/11865669/97421908-1158f080-1933-11eb-9ec0-a21212b33ec4.PNG)

** Targeted platforms (please complete the following information):**
Android, IOS

**Comment by illuminated** [comment]
Check if the behavior is the same in a stateless widget. If not, then on each state update of the page the widget tree redraw happens and the validation is fired as well.

**Comment by jigarfumakiya** [comment]
Hey @illuminated 
I have checked that is not happing in the stateless widget. but The question is why onInputValidated is fired in setState.

Now let's assume that I have setState in onInputChanged so when the number changes tree rebuild. But what if the user has already entered the number It's still calling both methods. (user is not entering anything )
Check below image

![number2](https://user-images.githubusercontent.com/11865669/97530783-dad5b100-19d8-11eb-9d70-dbd9c64a591b.png)


What I think is onInputChanged&onInputValidated should call only when there are any changes in the number or the user changes anything.
