### ISSUE TITLE
Country selection not working if initial value is set

### ISSUE THREAD

**Issue by Chris1234567899** [natintosh/intl_phone_number_input#122]
**Describe the bug**
When you set an initial value (the iso code), and you have setState() in onInputValidated, you cannot select another country.
If you do not set an initial value, this snippet works, if you do not call setState(), it works as well...

In a previous version this worked fine, so it must be a bug I guess.

**Package version**
0.5.2+2

**Flutter version**
Flutter 1.24.0-4.0.pre.41 • channel master

**To Reproduce**

 ```
InternationalPhoneNumberInput(
                  initialValue: PhoneNumber(isoCode: 'CO'),
                  onInputChanged: (PhoneNumber number) {
                    print("onInputChanged " + number.toString());
                    _phoneNumber = number.phoneNumber;
                  },
                  onInputValidated: (bool value) {
                    print("onInputValidated " + value.toString());
                    setState(() {
                      _phoneIsValid = value;
                    });
                  },
                ),
```

** Targeted platforms (please complete the following information):**
 -Tested in Android emulator

**Comment by illuminated** [comment]
@Chris1234567899 try with your `isoCode` string in lower case.

**Comment by Chris1234567899** [comment]
@illuminated 
no, lowercase does not work. With lower case it does not even pick the initial value.

**Comment by momtboy** [comment]
@illuminated @Chris1234567899 
I also encountered the same problem. After I set the initialValue, I found that selecting other countries was invalid.

**Comment by illuminated** [comment]
@momtboy @Chris1234567899 I'm not using statefull but stateless widgets and Bloc for state management. For me, the initial selection and the selection afterwards works.
Before I show this widget I set the initial country based on the user's current location and each change of value triggers a Bloc event to update the selected country. So, in my case, the control looks something like this:

```
InternationalPhoneNumberInput(
              onInputChanged: (PhoneNumber number) {
                context.bloc<SignInFormBloc>()
                  ..add(SignInFormEvent.phoneChanged(number.phoneNumber))
                  ..add(SignInFormEvent.countrySelected(state.allCountries
                      .firstWhere((element) => element.code == number.isoCode)
                      .name));
              },
              onInputValidated: (bool value) {
                validPhone = value;
              },
              selectorConfig: ipni.SelectorConfig(
                selectorType: ipni.PhoneInputSelectorType.BOTTOM_SHEET,
                useEmoji: true,
              ),
              ignoreBlank: false,
              autoValidateMode: AutovalidateMode.disabled,

              initialValue:
                  PhoneNumber(isoCode: state.selectedCountry.code),
              textFieldController: controller,

              ...

            ),
```

**Comment by momtboy** [comment]
> @momtboy @Chris1234567899 I'm not using statefull but stateless widgets and Bloc for state management. For me, the initial selection and the selection afterwards works.
> Before I show this widget I set the initial country based on the user's current location and each change of value triggers a Bloc event to update the selected country. So, in my case, the control looks something like this:
> 
> ```
>         InternationalPhoneNumberInput(
>               onInputChanged: (PhoneNumber number) {
>                 context.bloc<SignInFormBloc>()
>                   ..add(SignInFormEvent.phoneChanged(number.phoneNumber))
>                   ..add(SignInFormEvent.countrySelected(state.allCountries
>                       .firstWhere((element) => element.code == number.isoCode)
>                       .name));
>               },
>               onInputValidated: (bool value) {
>                 validPhone = value;
>               },
>               selectorConfig: SelectorConfig(
>                 selectorType: PhoneInputSelectorType.BOTTOM_SHEET,
>                 useEmoji: true,
>               ),
>               ignoreBlank: false,
>               autoValidateMode: AutovalidateMode.disabled,
> 
>               initialValue:
>                   PhoneNumber(isoCode: state.selectedCountry.code),
>               textFieldController: controller,
> 
>               ...
> 
>             ),
> ```

@illuminated It works, but I think the initialValue should not be changed by onInputChanged, it is just an initial default value, for example, I need to follow the current system language

**Comment by illuminated** [comment]
@momtboy I'm not affecting the initialValue with onInputChanged... I see the onInputChanged as an event triggered by either typing the phone number or by changing the country manually. That's why I fire two Bloc events in my code, so I could further update my own app logic with that change, not for updating the initialValue...

**Comment by Chris1234567899** [comment]
Well considering a lot of people are not using bloc, imo it should work with vanilla flutter out of the box.

As it did before, at least in version 0.3.0

**Comment by illuminated** [comment]
@Chris1234567899 I completely agree there. I haven't used this widget before so I cannot compare.

**Comment by reneveyj** [comment]
Worked around it by providing the current value of the phone number to the `initialValue` parameters:

```dart
InternationalPhoneNumberInput(
  onInputChanged: (phoneNumber) {
    setState(() {
      this._phoneNumber = phoneNumber;
    });
  },
  initialValue: this._phoneNumber ?? PhoneNumber(isoCode: 'US'), // Will be US (+1) by default
);
```

**Comment by mutumbakato** [comment]
> Worked around it by providing the current value of the phone number to the `initialValue` parameters:
> 
> ```dart
> InternationalPhoneNumberInput(
>   onInputChanged: (phoneNumber) {
>     setState(() {
>       this._phoneNumber = phoneNumber;
>     });
>   },
>   initialValue: this._phoneNumber ?? PhoneNumber(isoCode: 'US'), // Will be US (+1) by default
> );
> ```

This causes an infinite loop and you can't edit the phone number after input.

**Comment by nixcode1** [comment]
This ticket was closed without an fix or a workaround

Setting an initial value doesn't allow for any other countries to be selected

**Comment by philipgiuliani** [comment]
How am I supposed to set the initial phone number? I have the same issue... This "Workaround" causes an infinite loop as soon as a valid number is entered.
