### ISSUE TITLE
Dense Version

### ISSUE THREAD

**Issue by uzuki-P** [natintosh/intl_phone_number_input#124]
**Is your feature request related to a problem? Please describe.**
I need to add the input text to a tight space. The current design use too much space and I can't edit some padding. Like on the screenshot below, there's a sized box that I can't remove. 
![image](https://user-images.githubusercontent.com/16524713/97771686-18ba0d00-1b72-11eb-869d-74bf6aa226db.png)

**Describe the solution you'd like**
Add a new parameter something like `isDense: bool` and let us modify the padding using input decoration.

**Comment by natintosh** [comment]
Similar to #114.

@uzuki-P I've made an update on Github that has a new property called `spaceBetweenSelectorAndTextField`. This update should come with next update to the package.

104744e05012b6f7c9da3adebcd303c574b2e172
