### ISSUE TITLE
getRegionInfoFromPhoneNumber returns an error

### ISSUE THREAD

**Issue by erperejildo** [natintosh/intl_phone_number_input#125]
When calling `getRegionInfoFromPhoneNumber` if we pass a phone number without phone code it returns an error. We need to check if the number has a + in it before calling this function

**Comment by natintosh** [comment]
@erperejildo, Thanks for raising this issue but unfortunately Google's `libphonenumber` does not recognise a String without the `+` or without the `isoCode` passed into it as a phone number, that why you are always getting an exception.

**Comment by erperejildo** [comment]
Ok, so not related to this then
