### ISSUE TITLE
@natintosh, MIA?

### ISSUE THREAD

**Issue by illuminated** [natintosh/intl_phone_number_input#133]
Hey @natintosh, just wondering out loud if there's an issue with maintaining this repo or you'd need some help?

**Comment by natintosh** [comment]
Not really, I am currently working on the web version, a lot of people have been asking and it's a load of my time. No libphonenumber package for Flutter web, so I had build one. I have made lots of progress with that, I had a few issues at the start. Before the end of this month, I hope it would be ready.

**Comment by natintosh** [comment]
I could add you as a contributor if you would like, I will be happy to have someone to work with.

**Comment by natintosh** [comment]
![image](https://user-images.githubusercontent.com/27495055/99189477-a1839c00-2761-11eb-81a3-b4298ad55a9f.png)


Progress so far, but still loads of work to be done

**Comment by cedvdb** [comment]
> I could add you as a contributor if you would like, I will be happy to have someone to work with.

You could ask for maintainers. There are lots of PR hanging and I'm sure people would help, especially since it's such a succesful package

**Comment by natintosh** [comment]
#202. Hi, I am in need of co-contributors or co-maintainers. Please refer to #201 if you're interested
