### ISSUE TITLE
Emoji not rendering on some Android Devices 

### ISSUE THREAD

**Issue by muarachmann** [natintosh/intl_phone_number_input#137]
**Describe the bug**
Emoji flag seems not to work on some android devices

**Package version**
^0.5.0

**Flutter version**
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (10 weeks ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

**To Reproduce**
```
InternationalPhoneNumberInput(
       .....
       countries: ['CM'],
       selectorConfig: SelectorConfig(
              selectorType: PhoneInputSelectorType.BOTTOM_SHEET,
               useEmoji: true),
       ....
     ),
```

**Expected behavior**
The emoji flag is suppose to render or render the custom flag

**Screenshots**
![test](https://user-images.githubusercontent.com/16350814/99820550-3b2bbe80-2b51-11eb-9f16-567920af2f74.jpeg)

** Targeted platforms (please complete the following information):**
 - OS  - Android LG-K371, Android 6.0
 - Web [ ❌]

**Additional context**
This happens only on this device, i have tested on other android devices and they work. This just happens to be the case of this device. I don't know if it affects another android device or not.

**NB** When i don't use emoji it works well

**Comment by natintosh** [comment]
It seems as if the device doesn't support Flag emojis like on Windows PCs. 

For the emoji generation I basically use the code point system by convertiong the countryCode to symbols.

[Swift turn a country code into a emoji flag via unicode](https://stackoverflow.com/questions/30402435/swift-turn-a-country-code-into-a-emoji-flag-via-unicode)

 - [**United States**](https://emojipedia.org/flag-united-states/) `The Flag: United States emoji is a flag sequence combining 🇺 Regional Indicator Symbol Letter U and 🇸 Regional Indicator Symbol Letter S. These display as a single emoji on supported platforms.`
