### ISSUE TITLE
Other languages support

### ISSUE THREAD

**Issue by sabRou** [natintosh/intl_phone_number_input#141]
I'm developing my application in French. 
I would like to change the countries names list and the default text for the countries search dialog "Search by country name or dial..."  to french language. How can I do?

Thanks!

**Comment by natintosh** [comment]
@sabRou, you can update the default text for the search textfield by adding a `seachBoxDecorator` poperty
                  **searchBoxDecoration: InputDecoration(
                      labelText: 'Recherche par nom de pays ou indicatif'),**

for the French translation, set the `locale` to 
                  **locale: 'se',** 

![image](https://user-images.githubusercontent.com/27495055/102678316-d3947d80-41a7-11eb-8b1c-2905b7a1be79.png)

```dart 
InternationalPhoneNumberInput(
                  initialValue: number,
                  ignoreBlank: false,
                  autoValidateMode: AutovalidateMode.always,
                  textFieldController: controller,
                  focusNode: focusNode,
                  autoFocus: true,
                  inputDecoration:
                      InputDecoration(border: OutlineInputBorder()),
                  locale: 'fr',
                  searchBoxDecoration: InputDecoration(
                      labelText: 'Recherche par nom de pays ou indicatif'),
                  selectorConfig: SelectorConfig(
                    selectorType: PhoneInputSelectorType.BOTTOM_SHEET,
                  ),
                  onInputChanged: (PhoneNumber value) {},
                )
```

**Comment by sabRou** [comment]
it`s working. Thank you!
