### ISSUE TITLE
Trash log output: "Inserted Digits..."

### ISSUE THREAD

**Issue by agordeev** [natintosh/intl_phone_number_input#149]
**Describe the bug**
The library outputs a garbage logs in my console as I type:

```
flutter: Inserted Digits 6
flutter: Old start 14
flutter: New end 15
```

**Package version**
0.5.2+2

**Flutter version**
1.22.4

Also, the lib allows to enter 14 digits for US phone number, which is invalid. It should accept only 11 digits.

**Comment by natintosh** [comment]
Hi @agordeev, thanks for pointing that out. I have removed those logs and also you could modify the allowable length by setting the maxLength property of the package.

**Comment by muarachmann** [comment]
Hi @natintosh I still have this and since version  ` intl_phone_number_input: ^0.5.0` I first ignored this but my project has gone big and its really obstructing other logs
