### ISSUE TITLE
Extract country code from the input number. 

### ISSUE THREAD

**Issue by ayaanpathan** [natintosh/intl_phone_number_input#154]
**Describe the bug**
I want to extract the country code from the phone number which I input. Currently whole number is displayed with the country code. I want to send the country code to my backend, for that I will need to extract the country code from the number which I entered. (For eg. I entered '+91 8460020070') I want to extract just the '+91'. Can anyone help me how do i achieve that?

**Package version**
I'm using the latest package

The code i'm using. 

InternationalPhoneNumberInput(
            onInputChanged: (PhoneNumber number) {
              print(number.phoneNumber);
              setState(() {
                inputNumber = number.phoneNumber;
                print(inputNumber);
              });
              },
            formatInput: false,
            inputDecoration: InputDecoration(
                hintText: "Enter your mobile number",
              border: InputBorder.none
            ),
            onInputValidated: (bool value) {
              print(value);
            },
            // initialValue: PhoneNumber(isoCode: 'GB'),
            countries: ['GB','IN','US'],
            selectorConfig: SelectorConfig(
              selectorType: PhoneInputSelectorType.DIALOG,
              backgroundColor: Colors.white,
            ),
            ignoreBlank: true,
            maxLength: 15,
            autoValidateMode: AutovalidateMode.disabled,
            selectorTextStyle: TextStyle(color: Colors.black),
            hintText: "Enter your mobile number",
            textFieldController: _mobileNumberController,
            inputBorder: OutlineInputBorder(),
          ),

**Comment by natintosh** [comment]
```dart
   onInputChanged: (PhoneNumber number) {
       print(number.dialCode);
   },
```

All you need to do is to call `number.dialCode` from `onInputChange`

**Comment by ayaanpathan** [comment]
This worked! Thank you so much!! 👍
