### ISSUE TITLE
MTN Ghana new phone numbers doesn't work (059*******)

### ISSUE THREAD

**Issue by devsarfo** [natintosh/intl_phone_number_input#169]
**Describe the bug**
MTN Ghana new phone numbers doesn't work with the library, it reports that the phone number i invalid whiles it is valid eg. 0591234567 is a valid MTN Ghana phone number

**Package version**
intl_phone_number_input: ^0.5.2+2

**Flutter version**
flutter version:  1.22.5

**To Reproduce**
1. Install Plugin in Project
2. Enter any 10 digits starting with 059

**Expected behavior**
Phone number is not valid

**Comment by foxmedo** [comment]
did you find solution i have same issue on my country from same number format ?

**Comment by devsarfo** [comment]
Yes @foxmedo, I worked in the next update for me. Which country are you in so we help you

**Comment by corakwue** [comment]
observing this issue again for Ghana phone numbers starting with 059 or 025

Package version
intl_phone_number_input: ^v0.7.0+2 

Flutter version
flutter version: 2.10.3 (stable)

To Reproduce
Steps to reproduce the behavior:

Install Plugin in Project
Enter any 10 digits starting with 059 or 025
See error


Walkthrough shows `getParsedPhoneNumber` throws an exception and returns null

**Comment by josecaseiro** [comment]
How did you solve this problem?

**Comment by corakwue** [comment]
@josecaseiro set `errorMessage=null` which disables validation on the phone numbers
