### ISSUE TITLE
Crash when using phone PhoneInputSelectorType.DROPDOWN

### ISSUE THREAD

**Issue by martipello** [natintosh/intl_phone_number_input#173]
**Describe the bug**
crash when using phone PhoneInputSelectorType.DROPDOWN see attached screenshot

**Package version**
intl_phone_number_input: ^0.6.0

**Flutter version**
Flutter 1.25.0-8.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5d36f2e7f5 (4 weeks ago) • 2021-01-14 15:57:49 -0800
Engine • revision 7a8f8ca02c
Tools • Dart 2.12.0 (build 2.12.0-133.7.beta)

**To Reproduce**
start a new project
add your package
copy example and paste into main.dart
change selector config to drop down
selectorConfig: SelectorConfig(
                selectorType: PhoneInputSelectorType.DROPDOWN,
              ),

**Expected behavior**
expected to see a dropdown version of the country selector

**Screenshots**
https://drive.google.com/file/d/1-6hbm5hcKs0qHdx1WSEBvbzoHNx7TNLk/view?usp=sharing

**Comment by darkstarx** [comment]
That's because `Country` is being copied from `countries` in `showCountrySelectorBottomSheet` but has no ==operator for `DropdownButton` where a comparing the `value` with `items` is doing using ==operator.

Just implement `operator==` and `hashCode` in `Country` class.

**Comment by darkstarx** [comment]
Оh, sorry, I see that it has already been done in commit https://github.com/natintosh/intl_phone_number_input/commit/0e31a9a2d645e274569247d69b9cb46452c15e2e
