### ISSUE TITLE
Web platform error

### ISSUE THREAD

**Issue by imeDevelopers** [natintosh/intl_phone_number_input#179]
Android: +201234567890
Web: +2001234567890
Android is Correct ...

**Comment by abeticlairon** [comment]
Same issue on web; valid numbers on iOS and Android are marked as not valid in web. I believe it is due to the incorrect reference of the javascript scripts placed in index.html. Is there a direct link to the scripts instead of the current one mentioned in the pub.dev page

**Comment by Andranjo97** [comment]
Having the same issue here. It appears that in debug mode, the plugin works fine. Adding the `--release` tag causes the plugin to throw `Invalid phone number` all the time. Idk why though. It would be really good if they find a solution for this

**Comment by natintosh** [comment]
Here is the reference to the JS script. I didn't fully debug it with the `--release` tag. I apologise for the inconvenience.

```html
  <script src="assets/packages/libphonenumber_plugin/js/libphonenumber.js"></script>
  <script src="assets/packages/libphonenumber_plugin/js/stringbuffer.js"></script>
```

**Comment by imeDevelopers** [comment]
@natintosh @Andranjo97 @abeticlairon @sarbogast 
Now this problem affect android too, plugin version: 0.7.0+1

**Comment by tigrenok00** [comment]
@natintosh Hi, I have the same problem for the web, I'm using 0.7.0+2 and added the scripts above. For the same data on android isValidPhoneNumber() returns true but for web returns false. 
The control itself with AutovalidateMode is marked valid, but the isValidPhoneNumber() returns false.
