### ISSUE TITLE
onSaved callback in the InternationalPhoneNumberInput is not synchronous

### ISSUE THREAD

**Issue by sivaprasad-kiranum** [natintosh/intl_phone_number_input#180]
**Describe the bug**
When the form is saved in flutter with this._formKey.currentState.save(), the internal call for saving the phone number is using a future and so the value is not available right after the call to form save.

**Package version**
Your current version of the package [0.6.0]

**Flutter version**
Your current version of the Flutter SDK [1.22.6]

**To Reproduce**
```
void _signUp(BuildContext context) async {
    var _isValid = this._formKey.currentState.validate();
    if (_isValid) {
      this._formKey.currentState.save();
      print("Form is valid");
      final phoneAuthProvider =
          Provider.of<PhoneAuthProvider>(context, listen: false);
      print("In _signUp ${number.phoneNumber}");
      phoneAuthProvider.setValues(
          phoneNumber: number,
          onCodeSent: () {
            Navigator.of(context).pushNamed(VerifyPhoneScreen.ROUTE_NAME);
          });
    }
  }
```
The value inside the phoneAuthProvider is null for the phonenumber as it is not saved by the time the values are sent to the provider. It prints as null inside the provider.

**Expected behavior**
The save must be synchronous and the onSave must be called synchronous.

**Screenshots**
None.

** Targeted platforms (please complete the following information):**
 - OS [Android]
 - Web [❌]

**Additional context**
None.

**Comment by SergeyLabutin** [comment]
Same problem.

**Comment by natintosh** [comment]
Hi, I have replaced the asynchronous call with a simple regexp replace non-digit on any value `TextFieldController.Text` has.
