### ISSUE TITLE
Incompatible version 0.6.0 with cloud firestore 1.0.0  because of dependency to plugin_platform_interface 

### ISSUE THREAD

**Issue by jhandaya** [natintosh/intl_phone_number_input#184]
**Describe the bug**
Incompatible with cloud firestore 1.0.0

because of dependency to plugin_platform_interface 

Because cloud_firestore >=1.0.0 depends on cloud_firestore_platform_interface ^4.0.0 which depends on plugin_platform_interface ^2.0.0, cloud_firestore >=1.0.0 requires plugin_platform_interface ^2.0.0.
Because libphonenumber_platform_interface 0.2.0 depends on plugin_platform_interface ^1.0.3 and no versions of libphonenumber_platform_interface match >0.2.0 <0.3.0, libphonenumber_platform_interface ^0.2.0 requires plugin_platform_interface ^1.0.3.

Thus, cloud_firestore >=1.0.0 is incompatible with libphonenumber_platform_interface ^0.2.0.
And because libphonenumber_plugin 0.1.0 depends on libphonenumber_platform_interface ^0.2.0 and no versions of libphonenumber_plugin match >0.1.0 <0.2.0, cloud_firestore >=1.0.0 is incompatible with libphonenumber_plugin ^0.1.0.
And because intl_phone_number_input 0.6.0 depends on libphonenumber_plugin ^0.1.0 and no versions of intl_phone_number_input match >0.6.0 
<0.7.0, cloud_firestore >=1.0.0 is incompatible with intl_phone_number_input ^0.6.0.
**Package version**
0.6.0

**Flutter version**
Channel stable, 2.0.1

**To Reproduce**
1. pubspec yaml
2. add dependency to
      cloud_firestore: ^1.0.0
      intl_phone_number_input: ^0.6.0

3. Run flutter pub get

**Expected behavior**

Please update the dependency to the latest

**Screenshots**
Because cloud_firestore >=1.0.0 depends on cloud_firestore_platform_interface ^4.0.0 which depends on plugin_platform_interface ^2.0.0, cloud_firestore >=1.0.0 requires plugin_platform_interface ^2.0.0.
Because libphonenumber_platform_interface 0.2.0 depends on plugin_platform_interface ^1.0.3 and no versions of libphonenumber_platform_interface match >0.2.0 <0.3.0, libphonenumber_platform_interface ^0.2.0 requires plugin_platform_interface ^1.0.3.

Thus, cloud_firestore >=1.0.0 is incompatible with libphonenumber_platform_interface ^0.2.0.
And because libphonenumber_plugin 0.1.0 depends on libphonenumber_platform_interface ^0.2.0 and no versions of libphonenumber_plugin match >0.1.0 <0.2.0, cloud_firestore >=1.0.0 is incompatible with libphonenumber_plugin ^0.1.0.
And because intl_phone_number_input 0.6.0 depends on libphonenumber_plugin ^0.1.0 and no versions of intl_phone_number_input match >0.6.0 
<0.7.0, cloud_firestore >=1.0.0 is incompatible with intl_phone_number_input ^0.6.0.

** Targeted platforms (please complete the following information):**
 - OS [e.g. Android, iOS, ...]
 - Web [✔ or ❌]

**Additional context**

**Comment by madatr** [comment]
any plans to solve this?

**Comment by juanagu** [comment]
Same error here

**Comment by andeeDev** [comment]
Have the same error, is there a fix of it?

**Comment by bojidartonchev** [comment]
Any update on this?

**Comment by natintosh** [comment]
An update that resolves the conflict has been published.
