### ISSUE TITLE
Web release does not recognize the packages

### ISSUE THREAD

**Issue by Andranjo97** [natintosh/intl_phone_number_input#186]
**Describe the bug**
When launching a flutter web app, the script tags in the index.html don't recognize the paths of `packages/libphonenumber_plugin/js/libphonenumber.js` and `packages/libphonenumber_plugin/js/stringbuffer.js`. This happens when I launch the application with the `--release` tag.

**Package version**
intl_phone_number_input: ^0.6.0

**Flutter version**
```
Flutter 1.25.0-8.1.pre • channel unknown • unknown source
Framework • revision 8f89f6505b (3 months ago) • 2020-12-15 15:07:52 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)
```

**To Reproduce**
1. add the `--release` tag to `flutter run -d chrome`.
2. check console, shows errors of not recognizing scripts:
```
Refused to execute script from 'http://localhost:45109/packages/libphonenumber_plugin/js/libphonenumber.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```
```
Refused to execute script from 'http://localhost:45109/packages/libphonenumber_plugin/js/stringbuffer.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```
when interacting with the plugin
```
Uncaught PlatformException(error, ReferenceError: libphonenumber is not defined, null, null)
```

**Expected behavior**
This package should work in release mode as it works in debug mode.

** Targeted platforms (please complete the following information):**
 - OS [❌]
 - Web [✔]

**Comment by sabRou** [comment]
Hello,
I have a similar issue, when I run the app in release mode, package is not at all working for Android.
How did you did to fix the issue? please help I'm completely blocked here.
Thanks a lot in advance!

**Comment by Andranjo97** [comment]
Hi @sabRou. Hope this helps. I used another dependency `intl_phone_field: ^1.4.2`. However, the latter is not as complete as `intl_phone_number_input`. It's a pity not to have this library working.

**Comment by natintosh** [comment]
😅😅😅. I'm sorry about that, you should this instead

```html
  <script src="assets/packages/libphonenumber_plugin/js/libphonenumber.js"></script>
  <script src="assets/packages/libphonenumber_plugin/js/stringbuffer.js"></script>
```

I'll be closing this.

**Comment by sabRou** [comment]
Hello @natintosh, for me it's happening when I run on Android (not web) with release mode. What should I do? thanks

**Comment by Andranjo97** [comment]
Thanks @natintosh that seemed to be the problem!
