### ISSUE TITLE
Valid number does not validate on Chrome or Web

### ISSUE THREAD

**Issue by jasonkolodziej** [natintosh/intl_phone_number_input#20]
`hintText:` doesn't show up on any platforms... ): and on Web versions, it seems to not validate the phone )))):::::
<img width="1910" alt="Screen Shot 2020-02-08 at 2 46 45 PM" src="https://user-images.githubusercontent.com/42076058/74091851-3befda00-4a82-11ea-82b7-ef661f650e0a.png">
<img width="1599" alt="Screen Shot 2020-02-08 at 2 47 27 PM" src="https://user-images.githubusercontent.com/42076058/74091854-3eeaca80-4a82-11ea-89b9-20d87c61065e.png">
<img width="363" alt="Screen Shot 2020-02-08 at 2 48 42 PM" src="https://user-images.githubusercontent.com/42076058/74091855-40b48e00-4a82-11ea-9bdb-2da21f2e1035.png">

```
# sign_up.dart
PhoneNumber phone;
...
SizedBox(height: 20.0,),
                InternationalPhoneNumberInput(
                  onInputChanged: (PhoneNumber input){
                    setState(() => phone = input);
                  },
                  initialCountry2LetterCode: "US",
                  isEnabled: true,
                  selectorType: PhoneInputSelectorType.DIALOG,
                  autoValidate: true,
                  hintText: 'phone number',
                  errorMessage: "*invalid phone number",
                  onInputValidated: (val) => print(val),
                  formatInput: true,
                  inputDecoration: InputDecoration(border: UnderlineInputBorder()),
                ),
...
```

**Comment by natintosh** [comment]
Hi, @jasonkolodziej thanks for bringing this up. I will into to find the cause and fix it. Thank you.

**Comment by natintosh** [comment]
Hi, @jasonkolodziej I know this is coming late but it seems that the library I'm using does not have a platform channel support for  the web yet only android and iOS

**Comment by jasonkolodziej** [comment]
Thank you for this information! I greatly appreciate it!

*Jason Kolodziej*

Computer Science UG, '20 | Engineering IT

*Texas A&M* | College of Dwight Look Engineering

jasonkolodziej97@gmail.com | me@jasonkolodziej.com

cell +1 830.391.4180

**Comment by ammaratef45** [comment]
> Hi, @jasonkolodziej I know this is coming late but it seems that the library I'm using does not have a platform channel support for the web yet only android and iOS

What library are using that doesn't have a web support?

**Comment by natintosh** [comment]
Right now the library doesn't support web, but I've been working how to add web support for a while now. I'll make it available once it's ready, I am sorry about the inconvenience

**Comment by ammaratef45** [comment]
@natintosh I was asking because I wanted to help, I can make a PR if you told me what you need to add

**Comment by krisztianodor** [comment]
> Right now the library doesn't support web, but I've been working how to add web support for a while now. I'll make it available once it's ready, I am sorry about the inconvenience

Any update on this?

**Comment by jasonkolodziej** [comment]
Sorry, I do apologize. I do not remember which library it had pulled. It was some Web Assembly or C Library, it has been a while since messing with my repo.

**Comment by jasonkolodziej** [comment]
@krisztianodor  thank you!
