### ISSUE TITLE
PlatformException on empty phone string

### ISSUE THREAD

**Issue by PaulVipond** [natintosh/intl_phone_number_input#204]
Hi, really appreciate you getting out the latest version of this excellent package thanks :-)

**Describe the bug**

With the latest version I get the following error:

Exception has occurred.
PlatformException (PlatformException(NumberParseException, The string supplied did not seem to be a phone number., null, null))

whenever I select the country code pop-up, choose a country code and my telephone number is empty. If I then continue and type the first digit of my phone number I get 2 of these errors. After that there are no more errors if I complete the number.

**Package version**
0.7.0 - released yesterday

**Flutter version**
Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.18363.1316], locale en-GB)

**To Reproduce**
_Steps_

1. Phone number is empty.
2. Select country code drop-down
2. Select country (first platform error)
3. Type first digit of phone number (2 more platform errors)
4. Type remainder of number (no more errors)

_Code Snippet_

 ```
 InternationalPhoneNumberInput(
        spaceBetweenSelectorAndTextField: 0,
        hintText: currentInputState.inputPrompt,
        focusNode: focusNode,
        autoFocus: showKeyboard,
        cursorColor: AppState.i.chatFooterSendBoxCursorColour,
        textStyle: TextStyle(
          fontSize: AppState.i.chatFooterSendBoxFontSize,
          decoration: TextDecoration.none,
          color: AppState.i.chatFooterSendBoxFontColour
        ),
        inputBorder: InputBorder.none,
        onInputChanged: (PhoneNumber number) {
          onTextChanged(number.phoneNumber);
          currentPhoneNumber = number;
          print(number.phoneNumber);
        },
        onInputValidated: (bool value) {
          print(value);
        },
        selectorConfig: SelectorConfig(
          selectorType: PhoneInputSelectorType.BOTTOM_SHEET,
        ),
        ignoreBlank: false,
        autoValidateMode: AutovalidateMode.disabled,
        selectorTextStyle: TextStyle(color: Colors.black),
        initialValue: currentPhoneNumber,
        textFieldController: textController,
        formatInput: false,
        keyboardType: TextInputType.numberWithOptions(signed: true, decimal: true),
        //inputBorder: OutlineInputBorder(),
        onSaved: (PhoneNumber number) {
          //print('On Saved: $number');
        },
      )
```
_Use case_
Show country code + telephone number for input.
_Interaction with the widget_
?

**Expected behavior**
No error to occur.

**Screenshots**
N/A

** Targeted platforms (please complete the following information):**
 - Android

**Additional context**
N/A

**Comment by natintosh** [comment]
I am not able to recreate this issue. I am where the problem is from

**Comment by PaulVipond** [comment]
Thanks for the response. I'll see if I can put together a sample which recreates it.

**Comment by dutsky** [comment]
we have same issue and it seems exception pops up on vscode, but not on Android Studio.

**Comment by PaulVipond** [comment]
Yes, VS code for me too

**Comment by dfdgsdfg** [comment]
Same here on VS code.

**Comment by mikeknapp** [comment]
Has anyone been able to solve this?

**Comment by LloydCapson** [comment]
I'm having this same issue on both android studio and VS code.

**Comment by LloydCapson** [comment]
The issue seems to be caused by isValidPhoneNumber being passed a string phone number parameter with either 0 or 1 characters.

I created a [pull request](https://github.com/natintosh/intl_phone_number_input/pull/209) with temporary fix that just checks that the phone number is 2 or more characters log before allowing isValidPhoneNumber to be called. I don't know anything about the platform system to go deeper on it. This has fixed the issue on my end until someone with more knowledge than I can go deeper and figure out the real issue.
