### ISSUE TITLE
Cast error in dart file

### ISSUE THREAD

**Issue by naisarg011** [natintosh/intl_phone_number_input#206]
found this error when I was trying to enter a number (Os: - android ) , (Flutter version 2.0.1) (intl_phone_number_input: ^0.7.0 )

E/flutter (14238): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Future<bool?>' is not a subtype of type 'FutureOr<bool>' in type cast
E/flutter (14238): #0      _InputWidgetState.getParsedPhoneNumber (package:intl_phone_number_input/src/widgets/input_widget.dart:270:57)

This is the image of errors
![image](https://user-images.githubusercontent.com/53462326/113490035-563a1200-94e5-11eb-919c-cf5a9566d667.png)

error was showing in input_widget.dart file: - 
![image](https://user-images.githubusercontent.com/53462326/113490096-b29d3180-94e5-11eb-88a3-fc34e4729f5b.png)

**Comment by samuelstroschein** [comment]
I believe it's fixed but not published on pub.dev yet. See #203
