### ISSUE TITLE
Validator is defined with the wrong type

### ISSUE THREAD

**Issue by FRANIAZA** [natintosh/intl_phone_number_input#207]
The validator field is defined as 
```dart
String Function(String?)?
```
however I believe it should be defined as
```dart
String? Function(String?)?
```
otherwise if one wants to use a custom validator it is impossible to return null and one is forced to generate a validation error even if the input is valid.

**Comment by raduSoloso** [comment]
I also have this issue and it is quite an annyoing issue to have
