### ISSUE TITLE
How can i change the widget to appear right to left ?

### ISSUE THREAD

**Issue by Sathish9222** [natintosh/intl_phone_number_input#213]
**Describe the bug**
How can i change the widget to appear right to left ? Any Sample will be appreciated.

**Package version**
Your current version of the package [e.g. 0.1.2]

**Flutter version**
Your current version of the Flutter SDK [e.g. 1.11]

**To Reproduce**
1. Code Snippet
2. Use case
3. Interaction with the widget
5 ...

**Expected behavior**

**Screenshots**

** Targeted platforms (please complete the following information):**
 - OS [e.g. Android, iOS, ...]
 - Web [✔ or ❌]

**Additional context**

**Comment by natintosh** [comment]
For now, there is only small support for RTL and I have little experience with localization. But #187, was able to make it happen
