### ISSUE TITLE
Country selecting bottom sheet is overlapping with the status bar.

### ISSUE THREAD

**Issue by EshanNimesha01** [natintosh/intl_phone_number_input#220]
![IMG_20210522_223344](https://user-images.githubusercontent.com/68777800/119235205-f8be5b00-bb4e-11eb-9c01-52e224b2ef47.jpg)

**Comment by ChinaeduPascal** [comment]
Same here, I guess it has to be wrapped inside a `SafeArea Widget`.

**Comment by FarhanSyedain** [comment]
Resolved. Check #400
