### ISSUE TITLE
Country Codes Selector have bad performance...

### ISSUE THREAD

**Issue by RVYA** [natintosh/intl_phone_number_input#23]
The list for choosing country codes is slow and sometimes don't receive touchs...
When using;
- `PhoneInputSelectorType.DROPDOWN`, it takes about a second to open the list.
- `PhoneInputSelectorType.DIALOG`, slow launch as above, also takes a while to load the content of list too, pausing while scrolling…
- `PhoneInputSelectorType.BOTTOM_SHEET` have serious problems…

Tested on _Samsung Galaxy A10_, on _Debug_.

I think using a different method to load the elements, and using icon glyphs (like emoticons) instead of images will make a huge difference...

**Comment by CripyIce** [comment]
I'm experiencing this too.. For example, I think in `PhoneInputSelectorType.DIALOG` it would be better to use `ListView.builder` instead of `Column`.
Also, I think glyphs would be better too.

**Comment by natintosh** [comment]
Hi thanks for raising this up again, I know it took to long to respond but I've made attempts to reduce the load up delay of this package. I tried using Glyphs via custom fonts and icon sets but glyphs in Flutter are monochrome and Flutter does not support SVG out of the box. I am opened to suggestions if you any idea how I can make this happen, then I'll try to work on replacing Column with ListView.builder. Thanks

**Comment by natintosh** [comment]
> I'm experiencing this too.. For example, I think in `PhoneInputSelectorType.DIALOG` it would be better to use `ListView.builder` instead of `Column`.

Wow I made a lot of difference

**Comment by CripyIce** [comment]
@natintosh Glad I could help :)
Regards the glyphs, you're right, I guess it will require comparing the performance between using current PNG images and using SVG with external library (for example - `flutter_svg`).

**Comment by NoctisShadowzel** [comment]
@natintosh You may use flag emoticons in Noto Color Emoji font: https://www.google.com/get/noto/help/emoji/flags/ You will need to translate two letter code of country to regional indicator equivalent, but that must be easy. Also, I was forked this repository, but unfortunately couldn't find time to finish implementing glyphs...

**Comment by NoctisShadowzel** [comment]
Still I can share my code which uses this fonts flag characters, if you want.

**Comment by natintosh** [comment]
Hi @RVYA this would be great I will very much like to see that code. But not everyone would want to use emoticons. What I will do is to add an optional parameter to use emoticons.

**Comment by natintosh** [comment]
I recently added an option to use emoji flags. Thanks everyone
