### ISSUE TITLE
SafeArea for Search box

### ISSUE THREAD

**Issue by girish54321** [natintosh/intl_phone_number_input#285]
**Describe the bug**
Package is nice just SafeArea is missing 

**Package version**
`intl_phone_number_input: ^0.7.0+2`

**Flutter version**
`2.5.3`

**To Reproduce**
1. Example project
2. Run the app
3. Search for country code from modal
4. Swipe up the modal 
5. In Phone with notch (Pixel 3XL) 

**Expected behavior**
I shouldn't cut view for view

**Screenshots**
<img width="688" alt="Screenshot 2021-11-21 at 5 48 59 PM" src="https://user-images.githubusercontent.com/47414322/142762005-ea72f491-e85b-4af7-8b0b-caf3892d75f6.png">

** Targeted platforms (please complete the following information):**
 - OS [Android]
 - Web [NA]

**Additional context**
NA

**Comment by FarhanSyedain** [comment]
Resolved . Check #400
