### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by davarbla** [natintosh/intl_phone_number_input#293]
Hello,
Thank you for the package.
In France mobile phone numbers start with '06' and '07'.

06 is woking but 07 is giving 'invalid phone number'.
I tried to solve but I didn't find it.

Could you add 07 as a valid number in France please?

**Comment by dreking** [comment]
Try overriding libphonenumber package in your pubspec file

```
dependency_overrides:
  libphonenumber: ^2.0.2
```

**Comment by davarbla** [comment]
Thank you for your answer.

I am not using libphonenumber.

I am using intl_phone_number_input.

If I understood, you ask me to add a line 
libphonenumber: ^2.0.2

I will add it bellow intl_phone_number_input:   

intl_phone_number_input:   
libphonenumber: ^2.0.2

Is it right?

**Comment by dreking** [comment]
No, intl_phone_number_input package uses libphonenumber under the hood

This code below must be on the same indetention level as `dependencies`

**Comment by davarbla** [comment]
ok, I've done it, same level as dependencies: after 'dependencies' and before 'dev_dependencies'.

It has been taken:
>delete pubspec.lock
> flutter clean
> flutter pub get
Warning: You are using these overridden dependencies:
! libphonenumber 2.0.2

But, still having the 'Invalid phone number' message

**Comment by dreking** [comment]
Are you sure thats a valid france number?

**Comment by davarbla** [comment]
All mobile phone numbers in France starts with '06' or '07'

**Comment by dreking** [comment]
It seems '072' and '071' don't work well with this package. 
Did you try other valid numbers like 073...

**Comment by davarbla** [comment]
You're right!
070, 071 & 071 don't work.
The others do work.
Thank you for the support

**Comment by davarbla** [comment]
I have checked, it seems that 071 , 072 and some 070 are not in use in France.

So the library is fine, it's me than I am not ;-)

Thank you again !

**Comment by dreking** [comment]
I thought those numbers were kind of reserved too but weren't certain about it too.
Thanks for the update
