### ISSUE TITLE
Format input throws exception on web

### ISSUE THREAD

**Issue by debungle-it** [natintosh/intl_phone_number_input#297]
**Describe the bug**
When I set formatInuut: true on the web, I get the following error:
TypeError: Cannot read properties of undefined (reading 'AsYouTypeFormatter')
    at formatAsYouType (http://localhost:5000/app/packages/libphonenumber_web/src/libphonenumber_plugin.dart.lib.js:33:62)
    at formatAsYouType.next (<anonymous>)
    at runBody (http://localhost:5000/app/dart_sdk.js:40211:34)

**Package version**
  intl_phone_number_input: ^0.7.0+2

**Flutter version**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)

 - Web [✔]

**Additional context**

**Comment by manishkohbee** [comment]
Include these 2 lines in your `web/index.html`

`<script src="assets/packages/libphonenumber_plugin/js/libphonenumber.js"></script>
 <script src="assets/packages/libphonenumber_plugin/js/stringbuffer.js"></script>`
