### ISSUE TITLE
Uruguay number invalid

### ISSUE THREAD

**Issue by MathOliveira** [natintosh/intl_phone_number_input#303]
Hi, 

i am using this package to validate a latin america mobile phone number and i find a bug to validade numbers from Uruguay.

One case its this number: 982963xx (this last two x are normal numbers, i will not send the rest of number to not expose my user)

Package version: 0.7.0+2
Flutter version:  2.5.2
SO: Android 10

**Comment by MathOliveira** [comment]
wrongly opened

**Comment by josecaseiro** [comment]
How did you solved it?
