### ISSUE TITLE
toString() throws exception when phonNumber is null

### ISSUE THREAD

**Issue by jakub-cosmose** [natintosh/intl_phone_number_input#311]
**Describe the bug**
`phoneNumber` is a nullable value, but the method `toString` calls `phoneNumber!`. This causes the problem that printing the `PhoneNumber` e.g. for debugging purposes can crash the app.

**Package version**
v0.7.0+2

**Comment by bynalab** [comment]
Hi @jakub-cosmose, Thanks for reporting this. The issue has been resolved.
Should be available on the next update.

I'll go ahead and close this issue now.
Thanks
