### ISSUE TITLE
The search text if in `English`, even if another `locale` is used

### ISSUE THREAD

**Issue by asashour** [natintosh/intl_phone_number_input#327]
**Describe the bug**
When setting the `locale` to something like `ar`, one would expect that all messages are now in that locale.

**Package version**

**Flutter version**
`master` channel.

**To Reproduce**
```dart
          InternationalPhoneNumberInput(
            locale: 'ar',
```

**Expected behavior**
The message should be in arabie.

**Screenshots**
![image](https://user-images.githubusercontent.com/2410127/171872765-43306267-bb71-4116-b795-9c4ba9b460bf.png)

** Targeted platforms (please complete the following information):**
 - Web [✔] on Windows 10

**Comment by berkeugur** [comment]
```
InternationalPhoneNumberInput(
   searchBoxDecoration: InputDecoration(
      hintText: "Search Field Text",
      .
      .
      //more text field features
      .
      .
   ),
)

```

you can this.
