### ISSUE TITLE
Pub.dev Version Update

### ISSUE THREAD

**Issue by umutcoskun** [natintosh/intl_phone_number_input#341]
Thank you for fixed this issue: https://github.com/natintosh/intl_phone_number_input/issues/323

Please make it available on pub.dev so we can upgrade.

**Comment by emmaxCreative** [comment]
Waiting since months for this update. 
Hopefuly the new collaborators will also merge some of the other PRs soon.

**Comment by mayyaGhadeer** [comment]
Waiting  for this update

**Comment by SimonH-Zuma** [comment]
@emmaxCreative  Unless this library can be built and pub.dev upgraded, there seems no point in me testing, code reviewing and merging further PRs. Even now as a collaborator I have no powers to be able upgrade the pub.dev version, apologies :-(

**Comment by bynalab** [comment]
Thanks guys, I'm closing this since a new version has been uploaded to pub.dev
