### ISSUE TITLE
On iOS after the phone number is valed country dialcode is added to the number so it appears twice

### ISSUE THREAD

**Issue by hrishikeshpujari1902** [natintosh/intl_phone_number_input#371]
On iOS after the phone number is valed country dialcode is added to the number so it appears twice

**Comment by YaelAbdissa** [comment]
I am also having this issue @hrishikeshpujari1902 if you resolve this, can you please let me know how you resolved it?

**Comment by tigrenok00** [comment]
@hrishikeshpujari1902 What was your solution?
