### ISSUE TITLE
Doesn't support dark theme.

### ISSUE THREAD

**Issue by pretheesh** [natintosh/intl_phone_number_input#38]
The phone number can be styled using TextStyle, but the country code selected can't. A parameter like "countryCodeTextStyle" property will be helpful.
<img width="359" alt="Screen Shot 2020-04-25 at 11 45 09 AM" src="https://user-images.githubusercontent.com/2341255/80274273-41a4a580-86ea-11ea-876b-3d8bed0934ce.png">

**Comment by natintosh** [comment]
Hi @pretheesh thanks for raising this issue, you could wrap this in Theme widget and manipulate the TextStyle while I work on a fix for it.

**Comment by pretheesh** [comment]
@natintosh Thank you so much. Should I close this for now?
