### ISSUE TITLE
First digit getting removed

### ISSUE THREAD

**Issue by altafc22** [natintosh/intl_phone_number_input#40]
I'm trying to add phone number with country code +91 while i'm trying to type complete number at that time the first digit of mobile number vanished

**Comment by natintosh** [comment]
Hi, @altafc22  thanks for raising this issue. but I'm not sure I understand this but if I am wrong, correct me. I feel what you are saying is if you insert a complete phone number such as +91 xxx xxx xxxx, +91 is removed from the input field.

**Comment by alvinak** [comment]
I am also getting this issue.  Let me try to explain.
I am trying with country code +968 and I am trying to enter a phone number like this 94141414.
When I reach entering the number till 94141, first digit from the phone number (9) is getting removed automatically.
Please note that, there is no problem with country code.

**Comment by abdulwahid24** [comment]
I was also facing the same issue but If we keep `formatInput: false` then it works prefect.

**Comment by mikeRozen** [comment]
I have the same issue and `formatInput:false` still removes the first digit of the phone number
