### ISSUE TITLE
Soft keyboard automatically go back

### ISSUE THREAD

**Issue by usamabse048** [natintosh/intl_phone_number_input#41]
Whenever I tap on the text field to enter the keyboard appears for a moment than automatically go back due to which I am not able to write anything in text field.
I am getting following message in debug console
W/IInputConnectionWrapper(14564): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(14564): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(14564): getTextAfterCursor on inactive InputConnection

Following is my code 

 InternationalPhoneNumberInput(
                onInputChanged: (PhoneNumber input) {
                  setState(() => phone = input);
                },
                isEnabled: true,
                selectorType: PhoneInputSelectorType.DIALOG,
                autoValidate: true,
                hintText: 'phone number',
                errorMessage: "*invalid phone number",
                onInputValidated: (val) => print(val),
                
                formatInput: true,
               
              )

**Comment by vanshg395** [comment]
I am facing the same error, please some fix this soon.

**Comment by natintosh** [comment]
Hell @usamabse048  @vanshg395 I'm still trying to recreate this issue 
>Soft keyboard automatically go back

so far I've not been able to do say but note that those logs you see are Android generated logs.

 [https://github.com/flutter/flutter/issues/9471](https://github.com/flutter/flutter/issues/9471) 

[https://stackoverflow.com/questions/8122625/getextractedtext-on-inactive-inputconnection-warning-on-android](https://stackoverflow.com/questions/8122625/getextractedtext-on-inactive-inputconnection-warning-on-android)

**Comment by speroamey** [comment]
I am facing the same error...

**Comment by ZippyRainbow** [comment]
Hi @natintosh 

I was able to replicate the problem by adding a setState inside the onChange action, without this the problem doesn't occur.

Sorry, I am new to flutter development and am not familiar with how to create an Andriod Log.

```
import 'package:flutter/material.dart';
import 'package:intl_phone_number_input/intl_phone_number_input.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(title: Text('Demo')),
        body: MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<FormState> formKey = GlobalKey<FormState>();

  final TextEditingController controller = TextEditingController();
  String initialCountry = 'NG';
  PhoneNumber number = PhoneNumber(isoCode: 'NG');

  **String textPhoneNumber = '';**

  @override
  Widget build(BuildContext context) {
    return Form(
      key: formKey,
      child: Container(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            InternationalPhoneNumberInput(
              onInputChanged: (PhoneNumber number) {
                print(number.phoneNumber);
                **setState(
                        () => textPhoneNumber = number.phoneNumber);**
              },
              onInputValidated: (bool value) {
                print(value);
              },
              ignoreBlank: false,
              autoValidate: false,
              initialValue: number,
              textFieldController: controller,
              inputBorder: OutlineInputBorder(),
            ),
            RaisedButton(
              onPressed: () {
                formKey.currentState.validate();
              },
              child: Text('Validate'),
            ),
            RaisedButton(
              onPressed: () {
                getPhoneNumber('+15417543010');
              },
              child: Text('Update'),
            ),
          ],
        ),
      ),
    );
  }

  void getPhoneNumber(String phoneNumber) async {
    PhoneNumber number =
    await PhoneNumber.getRegionInfoFromPhoneNumber(phoneNumber, 'US');

    setState(() {
      this.number = number;
    });
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }
}
```

**Comment by natintosh** [comment]
Thanks for pointing that out @ZippyRainbow

**Comment by natintosh** [comment]
I found cause of this issue and fixed it, but I won't be able to publish an update because the fix causes a major bug. I'll still leave this issue opened till I publish a fix, for now try not using setState in onInputChange and pass a final  textEditingController field variable into the textFieldController argument

**Comment by tudor07** [comment]
@natintosh what is this major bug that it causes? I plan to use you git version since "don't use setState in onInputChange" fix does not work for me

**Comment by natintosh** [comment]
It turned out that the problem was with the key, I was using a `UniqueKey()` so the widget basic rebuilds every single time `setState` is called in `onInputChange` before but I've updated that. So with the updated, you can't update the `initialValue` your initial value with `setState` like as it is in the example but you use setState in `onInputChange`

**Comment by vanshg395** [comment]
I dont think that would solve the problem as i didnt use a ket at all for
this field still problem is occurring. Please provide a proper fix some and
push it as soon as possible.

**Comment by nipunasudha** [comment]
Happens when using inside a `flutter_form_builder` custom form field too. I guess it's because `flutter_form_builder` rebuilds it on change. Waiting for a fix 😢

**Comment by nipunasudha** [comment]
> It turned out that the problem was with the key, I was using a `UniqueKey()` so the widget basic rebuilds every single time `setState` is called in `onInputChange` before but I've updated that. So with the updated, you can't update the `initialValue` your initial value with `setState` like as it is in the example but you can use setState in `onInputChange`

Using a `UniqueKey` inside a stateless widget is a weird thing to do as I can understand because the widget becomes prone to unexpected rebuilds. Could you explain a bit about it's purpose? 

Also fixing it by replacing with a `ObjectKey(SomeClass)` can introduce bugs when there are multiple phone input widgets in the same view.

Please correct me if I'm wrong on these. Thank you.

**Comment by natintosh** [comment]
>Using a UniqueKey inside a stateless widget is a weird thing to do

You are without a doubt right, I also found it weird, but the issue there is the StatefulWidget it wraps. That widget is notorious for rebuilding itself and assigning a new label key. This behavior is the primary cause of this issue.

>replacing with a ObjectKey(SomeClass) can introduce bugs when there are multiple phone input widgets in the same view.

You are also right, this **could** also introduce a bug with multiple widgets in the same view

**Comment by natintosh** [comment]
Hi guys, I just published a fix to this issue. Thank you so much for your contributions. Cheers ✨

**Comment by natintosh** [comment]
> Hi guys, I just published a fix to this issue. Thank you so much for your contributions. Cheers ✨

To fix this issue I had to revert back to one of my previous builds that worked, then removed dependencies for providers and removed the `StatelessWidget` that nested this input widget

**Comment by natintosh** [comment]
I'll close the issue now. Please feel free to fork this repo to add new features and bugs or open a new issue if you encounter any problem
