### ISSUE TITLE
Need to be able to set the text style for the country code

### ISSUE THREAD

**Issue by emmett-deen** [natintosh/intl_phone_number_input#43]
I wanted to give the field a dark background so I need control over the country code color so that it is easily visible.

![image](https://user-images.githubusercontent.com/7634149/81220733-cb3c5900-8faf-11ea-9da3-ec66b26547b2.png)

**Comment by emmett-deen** [comment]
https://github.com/natintosh/intl_phone_number_input/pull/44

Opened a pull request with support for this

**Comment by natintosh** [comment]
Duplicate of #38

**Comment by natintosh** [comment]
Hi @emmett-deen I just publish an updated that has the feature you requested, thanks for the PR ✨
