### ISSUE TITLE
Migrate to `dlibphonenumber`

### ISSUE THREAD

**Issue by sashkent3** [natintosh/intl_phone_number_input#431]
**Is your feature request related to a problem? Please describe.**
`intl_phone_number_input` doesn't support Linux, macOS, Windows and WASM platforms because of dependency on `libphonenumber_plugin`. I propose to instead migrate this package to [dlibphonenumber](https://pub.dev/packages/dlibphonenumber) - a Dart port of [Google's libphonenumber library](https://github.com/google/libphonenumber).

**Describe the solution you'd like**
Remove dependency on `libphonenumber_plugin`, replace all relevant code with `dlibphonenumber`'s implementation.

**Describe alternatives you've considered**
Updating `libphonenumber_plugin` to support all relevant platforms seems to me like a lot more complex solution. Dependency on the JS version of `libphonenumber` is most concerning in the context of WASM.

**Additional context**
The migration is extremely straightforward.

**Comment by Brada-Groep** [comment]
I really want that wasm support and I hope that this can be implemented soon

**Comment by Padi142** [comment]
bump
