### ISSUE TITLE
selectorType: PhoneInputSelectorType.DIALOG

### ISSUE THREAD

**Issue by Abbykitty** [natintosh/intl_phone_number_input#45]
when I set: ' selectorType: PhoneInputSelectorType.DIALOG', I got the error massage :

flutter: Another exception was thrown: RenderBox was not laid out: RenderIntrinsicWidth#ef124 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#7bd8b relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#0a2be relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#c0116 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 322 pos 12: 'child.hasSize': is not true.
flutter: Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#c0116 relayoutBoundary=up2
flutter: Another exception was thrown: Updated layout information required for RenderFlex#2bef2 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.

what can I do to solve the problem?

**Comment by natintosh** [comment]
Hi, @Abbykitty  I recently publish and update that has a fix to this issue.

**Comment by IRiS-SK8** [comment]
Hi, I'm facing this same issue on latest #0.7.3+1 when using DIALOG and BOTTOM_SHEET
