### ISSUE TITLE
 Available Parameters 

### ISSUE THREAD

**Issue by Abbykitty** [natintosh/intl_phone_number_input#46]
How to check the detail of  Available Parameters？such as ，i want to set some properties of  inputDecoration，but i don't know how to do，because i don't know what properties does 'inputDecoration' have?

**Comment by natintosh** [comment]
Okay, so the input decoration available here also the same input decoration available for TextField and TextFormField. You can find available parameters from the [flutter doc](https://api.flutter.dev/flutter/material/InputDecoration/InputDecoration.html).
