### ISSUE TITLE
[UX] Prefix vertical-alignment when error message is shown

### ISSUE THREAD

**Issue by wiradikusuma** [natintosh/intl_phone_number_input#48]
When the input is invalid, an error message ("Invalid phone number") will appear. Unfortunately, the textbox+message combo makes the right-side taller and, since the prefix is vertically aligned, the layout looks weird. The prefix vertical alignment should stay the same.

In addition to that, it would be great if there's a flag to hide the error message (can't set it to null, will default to "Invalid phone number"). When this widget is used alone e.g. in a "log in by phone" screen, some apps prefer to show error dialog instead (for consistency with other screens perhaps), and the red-colored textbox outline should already give a clue.

**Comment by natintosh** [comment]
Please could shed more light because I still do not understand this, but I see what I can do.

**Comment by natintosh** [comment]
Hi @wiradikusuma  I  just pushed a fix for the alignment issue, but as for a flag to hide the error message, flutter does not support that out of the box to achieve this you'll have to modify `errorStyle` from `InputDecoration`. Thanks for your contribution
