### ISSUE TITLE
[UX] Changing country does not update formatted input

### ISSUE THREAD

**Issue by wiradikusuma** [natintosh/intl_phone_number_input#49]
When `formatInput` is true, the input is formatted according to the selected country (e.g. "1234" becomes "12 34" for Country X and "12-34" for Country Y). The problem is, when the country is changed, the input format is not updated (e.g. when changing Country X to Country Y, "-" should be added).

**Comment by natintosh** [comment]
Thank for raising this up, I'll look into this

**Comment by vanshg395** [comment]
I am facing same issue, this was not getting fixed so I made my own phone field. You can use it from here until this is fixed.

https://pub.dev/packages/intl_phone_field

**Comment by natintosh** [comment]
@wiradikusuma, I just pushed this feature, thanks for your contribution

**Comment by luis901101** [comment]
I´m still facing this issue using version 0.5.1

**Comment by vanshg395** [comment]
Try using these

https://github.com/vanshg395/intl_phone_field
