### ISSUE TITLE
Flags fail to load

### ISSUE THREAD

**Issue by StefanYYC** [natintosh/intl_phone_number_input#51]
Hey!

Thanks for the package!
Everything is working as expected, except for the differents assets that fail to load. I gave you a screenshot of the error I'm getting, it seems to be having issues with the ImageProvider as you can see.
![image](https://user-images.githubusercontent.com/32258096/82426636-66413280-9a88-11ea-9219-41e74c69ce25.png)
Any idea if you can fix it ? Or if it's possible to turn off the images ? I don't really need them anyway

thanks!

**Comment by natintosh** [comment]
Hello @StefanYYC thanks for raising this issue, I will check it out and get back to you as soon as I can.

**Comment by StefanYYC** [comment]
Just tried on another project and it worked there so its kinda weird

**Comment by natintosh** [comment]
Have you tried `flutter clean`

**Comment by StefanYYC** [comment]
I will try this out!

**Comment by natintosh** [comment]
Hi @StefanYYC,  any progress so far?

**Comment by StefanYYC** [comment]
Hi @natintosh , looks like it works for now!
Do you know how I can correct the height when the field isn't completed ?
![image](https://user-images.githubusercontent.com/32258096/82763394-9e899d80-9e07-11ea-922d-700805b7d8c0.png)
It looks great once its fulfilled as you can see
![image](https://user-images.githubusercontent.com/32258096/82763418-d1339600-9e07-11ea-8d4e-21ba77cfd8b9.png)
The diff can be slight to nice but the flag and the +33 aren't aligned exactly compared to the second screen

**Comment by natintosh** [comment]
Could you please code snippet for me to look into it as I am not completely sure what happened

**Comment by vanshg395** [comment]
I am facing same issue, this was not getting fixed so I made my own phone field. You can use it from here until this is fixed.

https://pub.dev/packages/intl_phone_field

**Comment by StefanYYC** [comment]
@vanshg395 Works like a charm!

**Comment by natintosh** [comment]
@StefanYYC, It seems as if you had a kind of validation error which most likely caused the alignment to be off

|   Without Validation Error |  With Validation Error |
|-------------|-----------|
|          <img src="https://user-images.githubusercontent.com/27495055/83172081-f4638b80-a10e-11ea-845d-dac88c3616e9.png" width="240" height="430" alt="Screenshot_1587652933"/>       |    <img src="https://user-images.githubusercontent.com/27495055/83172114-00e7e400-a10f-11ea-99bb-61f7308bfd20.png" width="240" height="430" alt="Screenshot_1587652933"/>         |

**Comment by natintosh** [comment]
Hi, @StefanYYC  I just pushed an update to my repo that fixes the alignment issue. Thanks for raising this issue, I really appreciate this.

| Update |
|---------|
|<img alt="Screenshot_1587652933" width="240" height="430" src="https://user-images.githubusercontent.com/27495055/83337094-88208d80-a2b0-11ea-879e-81aaebe996ef.png">|
