### ISSUE TITLE
initialCountry2letterCode alternative

### ISSUE THREAD

**Issue by mzafer** [natintosh/intl_phone_number_input#52]
Hi,

Thanks for the package. Any reason why initialCountry2letterCode parameter was removed and the alternative solution to set the initial country code ?

Thanks

**Comment by cornerman** [comment]
I got it working by providing an initial value for the phonenumber, which is not really intuitive when only having a country code, but it works:
```dart
InternationalPhoneNumberInput(
  ...
  initialValue: PhoneNumber(phoneNumber: "", dialCode: "", isoCode: countryCode)
)
```

**Comment by natintosh** [comment]
I am sorry the breaking changes,  it was recommended in issue #28. The idea was to allow initialValue and update the phone number rather than using the controller instance to update the phone number. @cornerman shared an example of how you can use the new initialValue parameter.

**Comment by mzafer** [comment]
Got it. Thanks both.
