### ISSUE TITLE
Keyboard refuses to show

### ISSUE THREAD

**Issue by wiradikusuma** [natintosh/intl_phone_number_input#54]
I have 2 alternating forms in a route, and this widget is in the 1st form. 

	SingleChildScrollView(
		child: _waitingPin ? _pinForm(ctx) : _phoneForm(ctx),
	),

Upon returning from the 2nd form (i.e. on error), the keyboard refuses to show. Please watch the screencast below for reproduction:

![Keyboard refuses to show](https://user-images.githubusercontent.com/481995/82592398-0c955100-9bcb-11ea-88ae-9cd83be7ad28.gif)

**Comment by natintosh** [comment]
Hi @wiradikusuma, I just published a fix. thanks for raising this issue ✨
