### ISSUE TITLE
textFieldController is only returning the phone number and not the country code

### ISSUE THREAD

**Issue by miller619** [natintosh/intl_phone_number_input#55]
printing the phone number inside onInputChanged is returning the expected number with country code, however passing the number through textFieldController is only returning the number without the country code to the TextEditingController().

**Comment by natintosh** [comment]
Hi @miller619, this is expected behavior. This is so because the `TextEditingController()` is working with the `TextField`, therefore any input the `TextField` has it what the `TextEditingController()` would return. I hope this helps

**Comment by miller619** [comment]
In that case how do I return the phone number along with the country code?

**Comment by natintosh** [comment]
Oh by returning do you mean updating ??

**Comment by miller619** [comment]
Yea.. like update the TextEditingController to save the phone number along with the country code. Because the controller only returns the number and not the country code.

**Comment by natintosh** [comment]
ok. So to updated the input and the country code selected just use setState on the initialValue, which accepts a phone number and iso code. I hope this helps

**Comment by miller619** [comment]
please take a look at this

`const InternationalPhoneNumberInput({
    Key key,
    this.selectorType,
    @required this.onInputChanged,
    this.onInputValidated,
    this.focusNode,
    this.textFieldController,
    this.onSubmit,
    this.keyboardAction,
    this.countries,
    this.textStyle,
    this.inputBorder,
    this.inputDecoration,
    this.searchBoxDecoration,
    this.initialCountry2LetterCode = 'NG',
    this.hintText = 'Phone Number',
    this.isEnabled = true,
    this.autoValidate = false,
    this.formatInput = true,
    this.errorMessage = 'Invalid phone number',
    this.ignoreBlank = false,
    this.locale,
  }) : super(key: key);`


There is no initialValue in the constructor.

**Comment by natintosh** [comment]
It seems you are using a previous version of the package, please update it to the latest version `intl_phone_number_input: ^0.4.2`

**Comment by miller619** [comment]
Updated. Now i have initialValue in constructor but still cannot get the value. Tried following your example again and again. Not leading me anywhere. I keep getting only the phone number without the coutrycode.

**Comment by inkersgithub** [comment]
I used the onInputChanged event as below
`PhoneNumber phoneNumber;
.
.
InternationalPhoneNumberInput(
                        .
                        .
                        onInputChanged: (number) {
                          setState(() {
                            phoneNumber = number;
                          });
                        },
                        .
                      )

void someFunction(){
     print(phoneNumber.dialCode);
}`

**Comment by girish54321** [comment]
Thanks, @inkersgithub worked for me 🎉
