### ISSUE TITLE
setting local language 

### ISSUE THREAD

**Issue by Abbykitty** [natintosh/intl_phone_number_input#57]
I want setting Chinese as the  local language ,so I add the code " locale:'fr_FR' " to InternationalPhoneNumberInput(), but it does not work.why? How can I set  local language ?

```
InternationalPhoneNumberInput(
              onInputChanged: (PhoneNumber number) {
                account = number.parseNumber();

              locale:'zh_CN',

              ignoreBlank: true,
              autoValidate: false,
              initialValue: PhoneNumber(isoCode: 'CN'),
              textFieldController: widget.controller,
              inputBorder: OutlineInputBorder(),
              selectorType: PhoneInputSelectorType.BOTTOM_SHEET,
              inputDecoration: InputDecoration.collapsed(
                border: UnderlineInputBorder(),
                hintText: allTranslations.text('phoneNumber'),
              ),
            ),
```

**Comment by natintosh** [comment]
Right now there is no translation available, The locale String field option was added for translation support.

**Comment by Abbykitty** [comment]
ok thanks发自我的iPhone------------------ Original ------------------From: Ogunye Nathaniel Oluwatobiloba  <notifications@github.com>Date: Tue,Jun 2,2020 3:12 AMTo: natintosh/intl_phone_number_input <intl_phone_number_input@noreply.github.com>Cc: pipixi <abby_kitty@sina.com>, Author <author@noreply.github.com>Subject: Re: [natintosh/intl_phone_number_input] setting local language  (#57)
Right now there is no translation available, The locale String field option was added for translation support.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/natintosh/intl_phone_number_input/issues/57#issuecomment-637050183",
"url": "https://github.com/natintosh/intl_phone_number_input/issues/57#issuecomment-637050183",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by natintosh** [comment]
Hi @Abbykitty  PR #83 and #88 solves this issue, stay tuned for an update. Thanks for your contribution

**Comment by erperejildo** [comment]
@natintosh this translates the country names but what about the "Search by country name or dial code" message?

**Comment by aatikakhan** [comment]
hey @erperejildo if you found solution for this then please share.

**Comment by erperejildo** [comment]
> hey @erperejildo if you found solution for this then please share.

nah, still looking

**Comment by alexsds** [comment]
@erperejildo @aatikakhan you can provide searchBoxDecoration and customize search input
