### ISSUE TITLE
The LengthLimitingTextInputFormatter is set to a fix lenght

### ISSUE THREAD

**Issue by wer-mathurin** [natintosh/intl_phone_number_input#58]
The use case:

If I select Canada as country, I want to limit the number to 12 digits.
+1-XXX-XXX-XXXX

**Comment by natintosh** [comment]
Hello @wer-mathurin, thanks for raising this issue but currently `intl_phone_number_input` is currently set to the recommended maximum length for a telephone number which is 15 with separators. For instance, as with the example you share if a user inserts that with the symbol (+) and separator (-) it sums up to 15.

**Comment by wer-mathurin** [comment]
But since we do not enter the + sign and the country code in the text box,
we are able to enter a longer number than allow for a specific country.

**Comment by natintosh** [comment]
Alright, I will add this feature and publish an update soon 👍👍👍 thanks again. I'll leave this issue opened till then

**Comment by natintosh** [comment]
Hi, I just publish an update with this feature. Thanks again for raising this
