### ISSUE TITLE
2 crashes

### ISSUE THREAD

**Issue by sgehrman** [natintosh/intl_phone_number_input#59]
Turn on All Exceptions and there are a few.

I try to type a number and after the first character, I get an index out of range. the offset below is 1 and the length of the string is 1 (first digit).  

  formatAsYouType(input: textToParse).then(
        (String value) {
          String parsedText = value.replaceFirst(dialCode, '').trim();

          int offset = newValue.selection.baseOffset;

          try {
            if (separatorChars.hasMatch(parsedText[offset])) {

Second crash. In InputWidget. If you don't set an initialValue, then didUpdateWidget tries to access null  oldWidget.initialValue.hash (initialValue is null).

 @override
  void didUpdateWidget(InternationalPhoneNumberInput oldWidget) {
    if (oldWidget.initialValue != widget.initialValue ||
        oldWidget.initialValue.hash != widget.initialValue.hash) {
      loadCountries(context);
      initialiseWidget();

**Comment by natintosh** [comment]
Hi @sgehrman  thanks for raising this, could  you share how I can reproduce the first issue, like the country iso code and the phone number you were trying to input

**Comment by natintosh** [comment]
Hi @sgehrman  PR #66  just fixed this issue, I didn't understand what it was at first. Thanks you, I'll be closing this now
