### ISSUE TITLE
Cannot choose a country code from dialog with search results

### ISSUE THREAD

**Issue by tneagu** [natintosh/intl_phone_number_input#63]
Hello,

The country picker dialog does not return a country if you use the search option.

Steps to reproduce:
1) setup the widget with an initialValue and selectorType: PhoneInputSelectorType.DIALOG

2) open country picker dialog and use search bar to search for any country different than the country in initial number. Select a country

3)the widget does not update with the selected country and reverts to initial value

**Comment by viktordineout** [comment]
Same problem here.

**Comment by ekoto4** [comment]
Didi anyone find a workaround for this?

**Comment by viktordineout** [comment]
@ekoto4 It works when I initialize a class member and reference initial value to that member.
`PhoneNumber initialValue = PhoneNumber(isoCode: 'IS', phoneNumber: "phonenr");`
`InternationalPhoneNumberInput(initialValue: initialValue)`

**Comment by ekoto4** [comment]
@viktordineout Okay thank you!
