### ISSUE TITLE
Could not find a way to customize left padding

### ISSUE THREAD

**Issue by tneagu** [natintosh/intl_phone_number_input#64]
Hello,

I cannot find a way to customize the padding from the left of the flag. Can you help please?

![image](https://user-images.githubusercontent.com/10370524/84862897-a80bcb80-b07c-11ea-9379-23de42858148.png)

**Comment by natintosh** [comment]
Hello @tneagu  I just published an update that removes the left padding from the selector button. Thanks for raising this issue
