### ISSUE TITLE
Incorrect cursor positioning while editing

### ISSUE THREAD

**Issue by darkstarx** [natintosh/intl_phone_number_input#65]
**Describe the bug**
If you edit a number in the middle, the cursor jumps to incorrect position.

**Package version**
Version is 0.4.5

**Flutter version**
Version of the Flutter SDK is 1.19.0-4.1.pre

**To Reproduce**
1. Set the phone number "910 111-11-11".
2. Move cursor to "0" and delete it.
3. Type any digit (say "5").
Actual position will be 6.

**Expected behavior**
The cursor position should be 3.

** Targeted platforms (please complete the following information):**
Any platform.

**Additional context**
See `as_you_type_formatter.dart`
```
          try {
            if (separatorChars.hasMatch(parsedText[offset])) {       ///< Here the bug!
              offset += 3;
            } else {
              offset += 1;
            }
          } on RangeError {}
```
offset = 3;
parsedText[offset] = space
space is not digit (see `final RegExp separatorChars = RegExp(r'[^\d]+')`)

So, what does this mean? Why is the offset +3? This is pretty weird code.

**Comment by darkstarx** [comment]
I think the algo should be like this:
1. Extract the inserted string (substring of newValue between oldValue.selection.start and newValue.selection.end).
2. Remove all non digit chars from this substring.
3. In closure start finding inserted digits from position oldValue.selection.start in parsedText, one by one, skipping non digits chars.
4. When last digit of substring will be found, it's position is actual offset for new selection.

**Comment by fonkamloic** [comment]
The problem still exists in version ^0.4.6+2 when using 'CM' country code. And apparently, a user can move cursor position with a finger.

**Comment by fonkamloic** [comment]
I'm temporarily solving the problem using the following code snippet in onChange callback
` _phoneNumberController.selection = TextSelection.collapsed( offset: _phoneNumberController.text.length );`

**Comment by ClemaX** [comment]
I've got an issue when using +33(FR) and repeating the same character like +330000
