### ISSUE TITLE
When formatInput is true some countries coutry code is injected every key press

### ISSUE THREAD

**Issue by edex96** [natintosh/intl_phone_number_input#67]
**Description**
'formatInput' is not working same for all countries for example:
Working fine for: **+90, +672, +297**
Doesn't work for: **+1264, +1268, +1246**
Every key press injects the country code for example **+1264** into the text field

**Package version**
0.4.5

**Flutter version**
Flutter 1.20.0-1.0.pre • channel dev

**To Reproduce**
Use the given example code from pub.dev 
Select a country for ex: '+1264'
Type a phone number

**Expected behavior**
I expect it to behave the same for all countries

 **Targeted platforms**
 OS [Android, iOS]

**Comment by troyanskiy** [comment]
Same issue here

**Comment by troyanskiy** [comment]
The issue is related to the dependent library https://github.com/emostar/flutter-libphonenumber/issues/12

**Comment by zanesc** [comment]
Same issue.
