### ISSUE TITLE
Initial Country

### ISSUE THREAD

**Issue by rithviknishad** [natintosh/intl_phone_number_input#68]
**Description**
Unable to set initial country.
I'm not sure if this is a bug or a feature request.

**Versions:**
Tried on both  0.4.6+2, 0.4.6

**Flutter version**
Flutter 1.17.4

**To Reproduce**
```
InternationalPhoneNumberInput(
  textFieldController: phoneNumberController,
  locale: 'IN', // tired with '+91', 'IND' also and even setting initialValue with a dummy valid phone number with +91 country code too...
  selectorType: PhoneInputSelectorType.DIALOG,
  autoFocus: true,
  //onInputChanged: (PhoneNumber number) => phoneNumber = number.phoneNumber,
  ignoreBlank: false,
  autoValidate: false,
  textStyle: _textStyle,
  selectorTextStyle: _textStyle,
  inputDecoration: _inputDecoration('Phone Number'),
),
```

**Expected behavior**
Initial Country should be shown on build

** Targeted platforms (please complete the following information):**
 - OS: Android

**Comment by natintosh** [comment]
@rithviknishad  there is an initial value property that accepts a phone number object for instance

```dart
​InternationalPhoneNumberInput(
  textFieldController: phoneNumberController,
  locale: 'IN', // tired with '+91', 'IND' also and even setting initialValue with a dummy valid phone number with +91 country code too...
  selectorType: PhoneInputSelectorType.DIALOG,
  autoFocus: true,
  //onInputChanged: (PhoneNumber number) => phoneNumber = number.phoneNumber,
  ignoreBlank: false,
  autoValidate: false,
  textStyle: _textStyle,
  selectorTextStyle: _textStyle,
  inputDecoration: _inputDecoration('Phone Number'),
  initialValue: Phone number(isoCode: 'IN', phoneNumber: '555-5555-5555')
),

```

I hope this helps

**Comment by rithviknishad** [comment]
> @rithviknishad there is an initial value property that accepts a phone number object for instance
> 
> ```dart
> ​InternationalPhoneNumberInput(
>   textFieldController: phoneNumberController,
>   locale: 'IN', // tired with '+91', 'IND' also and even setting initialValue with a dummy valid phone number with +91 country code too...
>   selectorType: PhoneInputSelectorType.DIALOG,
>   autoFocus: true,
>   //onInputChanged: (PhoneNumber number) => phoneNumber = number.phoneNumber,
>   ignoreBlank: false,
>   autoValidate: false,
>   textStyle: _textStyle,
>   selectorTextStyle: _textStyle,
>   inputDecoration: _inputDecoration('Phone Number'),
>   initialValue: PhoneNumber(isoCode: 'IN', phoneNumber: '555-5555-5555')
> ),
> ```
> 
> I hope this helps

Thank you so much...  :)
