### ISSUE TITLE
Target of URI doesn't exist: 'package:intl_phone_number_input/intl_phone_number_input.dart'.

### ISSUE THREAD

**Issue by lohithkumar95** [natintosh/intl_phone_number_input#71]
i tried using the plugin but cant even import it.
it gives the below error.

`Target of URI doesn't exist: 'package:intl_phone_number_input/intl_phone_number_input.dart'.`

`intl_phone_number_input: ^0.4.6+2` is the version i am using.

**Comment by natintosh** [comment]
Hi, Have you tried `flutter packages get` on your terminal or cmd

**Comment by lohithkumar95** [comment]
Hi, Yes i have done it.

**Comment by lohithkumar95** [comment]
hi @natintosh sorry, when i tried that i get the below error.

```
Because intl_phone_number_input >=0.4.4 depends on equatable ^1.2.0 and shaw_mobile_app_flutter depends on equatable ^0.2.0, intl_phone_number_input >=0.4.4 is forbidden.
So, because shaw_mobile_app_flutter depends on intl_phone_number_input ^0.4.6+2, version solving failed.
Running "flutter pub get" in shaw_mobile_app_flutter...                 
pub get failed (1; So, because shaw_mobile_app_flutter depends on intl_phone_number_input ^0.4.6+2,
version solving failed.) 
```

**Comment by natintosh** [comment]
Oh thanks for pointing that out, I'll have to update my dependency. I'll push an update before EOD.

**Comment by natintosh** [comment]
@lohithkumar95, After reviewing this issue I discovered that  `shaw_mobile_app_flutter` support an older version of equatable ^0.2.0 that `intl_phone_number_input` never supported, and due to Dart Lang not supporting multiple packages `flutter packages get` failed. I am sorry about the inconvenience and thank you for your contribution.
