### ISSUE TITLE
Exception when validating phone number

### ISSUE THREAD

**Issue by lecuivre-alban** [natintosh/intl_phone_number_input#72]
**Bug description**
The bug occur in a quite specific scenario.

An exception is thrown when validating a phone number with a length of one digit.

Another exception occur when you start typing your phone number then delete all the text, an exception is thrown when validating an empty (or length==1) phone number. I think this second one might be linked to the first one so fixing the first one might also solve this one.

Exception :
```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: PlatformException(invalid_phone_number, Invalid Phone Number, null)
#0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
#1      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:159
<asynchronous suspension>
#2      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:332
#3      PhoneNumberUtil.getRegionInfo 
package:libphonenumber/libphonenumber.dart:61
#4      PhoneNumber.getRegionInfoFromPhoneNumber 
package:intl_phone_number_input/…/utils/phone_number.dart:41
#5      PhoneNumber.getParsableNumber 
package:intl_phone_number_input/…/utils/phone_number.dart:60
#6      _InputWidgetState.initialiseWidget 
package:intl_phone_number_input/…/widgets/input_widget.dart:262
#7      _InputWidgetState.didUpdateWidget 
package:intl_phone_number_input/…/widgets/input_widget.dart:251
#8      StatefulElement.update (packa<…>
```
**Package version**
`0.4.6+2`

**Flutter version**
```
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.5 19F101, locale
    fr-FR)
    • Flutter version 1.19.0-4.3.pre at [...]
    • Framework revision 8fe7655ed2 (9 days ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)
```

**Code snippet**
```dart
InternationalPhoneNumberInput(
  focusNode: phoneFocusNode,
  keyboardAction: TextInputAction.done,
  selectorButtonOnErrorPadding: 0,
  onInputChanged: (p) {
    phone = p.phoneNumber;
  },
  onInputValidated: (v) {
    phoneIsValid = v;
  },
  countries: ['FR'],
  initialValue: PhoneNumber(phoneNumber: phone, isoCode: 'FR'),
  inputDecoration: InputDecoration(
    hintText: 'Numéro de téléphone',
    hintStyle: TextStyle(
      color: Colors.grey,
    ),
    errorStyle: TextStyle(height: 0),
  ),
  errorMessage: '',
),
```

**Targeted platforms**
 - Android & iOS

**Comment by natintosh** [comment]
Hi, @lecuivre-alban thanks for raising this issue. I reviewed this issue and I was not able to reproduce this error, so I traced error you got and it turned out that it was an error from ["libphonenumber"](https://pub.dev/packages/libphonenumber).

**Comment by ClemaX** [comment]
Hi @natintosh, can you describe the behaviour that needs to be changed on 'libphonenumber'? I'm trying to fix the issue locally to provide a pull request but I'm not sure which value PhoneNumberUtil.getRegionInfo should return in case of 'invalid number' PlatformError.

**Comment by ClemaX** [comment]
@lecuivre-alban Maybe you can try again with the latest intl_phone_number_input and libphonenumber.
