### ISSUE TITLE
Please include textInputAction, onFieldSubmitted as we have for TextFormField control.

### ISSUE THREAD

**Issue by prileep** [natintosh/intl_phone_number_input#73]
Please see the example below. We have below parameters for TextFormField control. Can you include this for InternationalPhoneNumberInput ?

TextFormField(
	textInputAction: TextInputAction.next,
	onFieldSubmitted: (val) {
        FocusScope.of(context).requestFocus(<focus node>);
},

**Comment by natintosh** [comment]
Hi, @prileep I just added onFieldSubmitted property, textInputAction already exist as keyboardAction. Thanks for your contribution
