### ISSUE TITLE
BottomDialogSheet does not show countries names, just an icon

### ISSUE THREAD

**Issue by ghostmane0404** [natintosh/intl_phone_number_input#74]
**Describe the bug**

**Package version**
Your current version of the package [e.g. 0.1.2]

**Flutter version**
Your current version of the Flutter SDK [e.g. 1.11]

**To Reproduce**
1. Code Snippet
2. Use case
3. Interaction with the widget
5 ...

**Expected behavior**

**Screenshots**

** Targeted platforms (please complete the following information):**
 - OS [e.g. Android, iOS, ...]
 - Web [✔ or ❌]

**Additional context**

**Comment by natintosh** [comment]
Hello @ghostmane0404 I feel you should try cleaning up your project with flutter clean `flutter clean` or confirm that your textTheme style doesn't have white as it's font color
