### ISSUE TITLE
Bottomsheet view and keyboard input 

### ISSUE THREAD

**Issue by hoponaillc** [natintosh/intl_phone_number_input#78]
BottomSheet

![image](https://user-images.githubusercontent.com/66429728/87505136-1caf3700-c636-11ea-9714-7f4e462f02e2.png)

When we type on the keyboard, it just hides the entire bottom sheet. It will be great to adjust the bottom sheet height if there is keyboard input so that user can see what they types. 

![image](https://user-images.githubusercontent.com/66429728/87505166-2c2e8000-c636-11ea-886b-22b8092855c3.png)

**Comment by Susheelkaram** [comment]
Working on this issue
