### ISSUE TITLE
get Input from the spinner list 

### ISSUE THREAD

**Issue by johnmelodyme** [natintosh/intl_phone_number_input#84]
```get Input from the spinner list ``` 
to print out

**Comment by johnmelodyme** [comment]
Get country code , it seems I cant get it , any idea ?

**Comment by darkstarx** [comment]
Hi!
Actually you can do this like this
```
      onInputChanged: (number) {
        phoneValue = number;
        print('dial code: ${phoneValue.dialCode}, counrty code: ${phoneValue.isoCode}');
      },
```

**Comment by johnmelodyme** [comment]
> Hi!
> Actually you can do this like this
> 
> ```
>       onInputChanged: (number) {
>         phoneValue = number;
>         print('dial code: ${phoneValue.dialCode}, counrty code: ${phoneValue.isoCode}');
>       },
> ```

thank you
