### ISSUE TITLE
Focus issue during flutter integration tests

### ISSUE THREAD

**Issue by FrantisekGazo** [natintosh/intl_phone_number_input#92]
**Describe the bug**
When using flutter integration tests, the phone number is not entered. The TextField gets focused correctly (= I can see the cursor there) but no text is entered.

**Package version**
`0.4.6` and above. (was working fine on 0.4.5)

**Flutter version**
Tested on 1.17.5 and 1.20.2 - both had this issue.

**To Reproduce**
I created this repo so that you can easily try it: https://github.com/FrantisekGazo/intl_phone_number_input_example
It contains integration test for regular `TextField` and the `InternationalPhoneNumberInput`. There is no issue with the regular TextField.

- clone the repo
- run `flutter drive --target=test_driver/main.dart`

**Expected behavior**
The text should be entered.

**Screenshots**
<img src="https://user-images.githubusercontent.com/5168594/91179445-11f9be80-e719-11ea-8417-befad613711f.png" width="200" />

** Targeted platforms (please complete the following information):**
I only tried android.

**Comment by natintosh** [comment]
Hi @FrantisekGazo, check out this link on samples for integration test. [Samples](https://github.com/natintosh/intl_phone_number_input/tree/develop/example/test_driver)
