### ISSUE TITLE
SearchBoxDecoration is not working

### ISSUE THREAD

**Issue by andoutica** [natintosh/intl_phone_number_input#93]
When I applied searchBoxDecoration to InternationalPhoneNumberInput, nothing happen. 
I want to change the color but I don't know how.

**Comment by natintosh** [comment]
@andoutica thanks for raising this issue, you basically have to pass `InputDecoration` into the searchBoxDecoration parameter and set whichever border that you would like to modify for this case I think you will have to modify `enableBorder`, `focusBorder`, and `border`

**Comment by andoutica** [comment]
Sorry, that's my fault.
I'm looking for solution to set decoration for country dropdown view , but I'm wrong with searchBoxDecoration which working with dialog.
By the way, can you add a property to allow user can change country decoration.
Something like that
<img width="212" alt="Screen Shot 2020-09-02 at 9 21 44 PM" src="https://user-images.githubusercontent.com/7821844/91996146-dc7d5280-ed62-11ea-8097-b7a1597b1660.png">

**Comment by natintosh** [comment]
Flutter does not support dropdown decoration yet, the only two options available are Underline and Hide Underline for the dropdown button.

I think I can figure something out but not soon. I have a pending update that I've been delaying for a while now and lots of office work to do. Thanks
