### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by cmorsucci** [natintosh/intl_phone_number_input#95]
**Describe the bug**
The following assertion was thrown resolving an image codec:
Unable to load asset: packages/intl_phone_number_input/assets/flags/pt_br.png

**Package version**
intl_phone_number_input: ^0.5.0

**Flutter version**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale it-IT)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)

**Targeted platforms (please complete the following information):**
iOS (tested)

**Comment by fluxion8** [comment]
same

**Comment by derens99** [comment]
I am getting this as well. Have you resolved the error?

**Comment by fluxion8** [comment]
> I am getting this as well. Have you resolved the error?

Yes.I resolved

1) Download files directly from Github
2) Copy library to local folder
3) Add local path instead pub.dev url to pubspec
4) Finally change assets folder

**Comment by muarachmann** [comment]
> **Describe the bug**
> The following assertion was thrown resolving an image codec:
> Unable to load asset: packages/intl_phone_number_input/assets/flags/pt_br.png
> 
> **Package version**
> intl_phone_number_input: ^0.5.0
> 
> **Flutter version**
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale it-IT)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.7)
> [✓] Android Studio (version 4.0)
> 
> **Targeted platforms (please complete the following information):**
> iOS (tested)

Did you restart your app, quit it and restart all over

**Comment by cmorsucci** [comment]
yes, i tried everything .. i think the library is not updated on pub.dev so maybe it is enough that the developers of this package update it there.

**Comment by muarachmann** [comment]
Weird, I just installed it today I got the error, but after I stopped my app and restarted it, it worked, maybe try uninstalling and re-installing the app

**Comment by subhendukundu** [comment]
Facing the same issue. Even after stopping the app, restarted it or reinstalling.
It's still throwing error. :(

**Comment by derens99** [comment]
I've fixed the error by adding the flag png in. The fixed fork can be found here. https://github.com/derens99/intl_phone_number_input

In the pubspec.yaml, include this
international_phone_input:
    git:
      url: https://github.com/derens99/intl_phone_number_input

**Comment by natintosh** [comment]
Apologies. I just published an update with the fix all thanks to everyone on this thread.

**Comment by kaksv** [comment]
Also got the error in 2022

**Comment by kaksv** [comment]
But I terminated and restarted my App and It worked. Thank you
