### ISSUE TITLE
Dismiss Bottom Sheet Modal

### ISSUE THREAD

**Issue by muarachmann** [natintosh/intl_phone_number_input#98]
**Describe the bug**
Bottom sheet doesn't close up on tap outside the target area even when I set `ignoreBlank: true`

**Package version**
0.5.0

**Flutter version**
1.17.1

**To Reproduce**
```
InternationalPhoneNumberInput(
                            onInputChanged: (PhoneNumber number) {
                              print(number.phoneNumber);
                            },
                            onInputValidated: (bool value) {
                              print(value);
                            },
                            ignoreBlank: true,
                            autoValidate: true,
                            selectorTextStyle: TextStyle(color: Colors.black),
                            initialValue: mobilePhoneNumber,
                            selectorConfig: SelectorConfig(
                              selectorType: PhoneInputSelectorType.BOTTOM_SHEET,
                            ),
                            textFieldController: controller,
                            inputBorder: OutlineInputBorder(),
                          ),
```

**Expected behavior**
Close bottom sheet modal when click on other parts of the screen

**Screenshots**
<img width="303" alt="Screen Shot 2020-09-09 at 3 54 00 PM" src="https://user-images.githubusercontent.com/16350814/92617058-d46b6880-f2b6-11ea-90ef-6d6500f5a80c.png">

** Targeted platforms (please complete the following information):**
 - OS [e.g. Android, iOS, ...]
 - Web [✔ or ❌]

**Additional context**

**Comment by AnasMasri** [comment]
+1 to support closing bottom sheet on outside click. 
btw `ignoreBlank` flag has nothing to do with bottom sheet, it's a validation related flag to accept blank phone number when validator gets called.

**Comment by muarachmann** [comment]
> +1 to support closing bottom sheet on outside click.
> btw `ignoreBlank` flag has nothing to do with bottom sheet, it's a validation related flag to accept blank phone number when validator gets called.

Yes you are right. I did notice that later.

**Comment by ZackMitkin** [comment]
Still not implemented :/
